name: Check VppIdServer values

on:
  push:
    paths:
      - 'app/src/main/java/es/jvbabi/vplanplus/shared/data/VppIdServer.kt'
      - '.github/workflows/vppIdServer.yml'

jobs:
  check-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check scheme and host values
        run: |
          SCHEME=$(grep -oP 'private const val scheme = "\K[^"]*' app/src/main/java/es/jvbabi/vplanplus/shared/data/VppIdServer.kt)
          HOST=$(grep -oP 'private const val host = "\K[^"]*' app/src/main/java/es/jvbabi/vplanplus/shared/data/VppIdServer.kt)
          if [[ "$SCHEME" != "https" || "$HOST" != "id.vpp.jvbabi.es" ]]; then
            echo "Scheme or host values are incorrect"
            exit 1
          fi
